services:
  web:
    build:
      context: .
      target: prod
    container_name: ${PROJECT_NAME?PROJECT_NAME must be set}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${DOMAIN_NAME?DOMAIN_NAME must be set}`)"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=https"
      - "traefik.http.routers.${PROJECT_NAME}.tls=true"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=80"
    networks:
      - proxy-public

networks:
  proxy-public:
    external: true
    name: ${TRAEFIK_NETWORK?TRAEFIK_NETWORK must be set}
